from pynput.keyboard import Key, Controller
from pynput import keyboard
import time

time.sleep(2)
keyboard = Controller()
str = "Okay, I know this is a really bad idea but I'm already here so Here we fuckin’ go Rawr ​x3 nuzzles, pounces on you, uwu you so warm (Ooh) Couldn't help but notice your bulge from across the floor Nuzzles your necky wecky-tilde murr-tilde, hehe Unzips your baggy ass pants, oof baby you so musky Take me home, pet me, and make me yours and don't forget to stuff me See me wag my widdle baby tail all for your buldgy-wuldgy Kissies and lickies your neck I hope daddy likies Nuzzles and wuzzles your chest (Yuh) I be (Yeah) gettin’ thirsty. Hey, I got a little itch, you think you can help me? Only seven inches long, uwu, please adopt me Paws on your buldge as I lick my lips (UwU, punish me please) 'Bout to hit 'em with this furry shit (He don't see it comin') "
str2 = "What the fuck did you just fucking say about me, you little bitch? I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Quaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of spies across the USA and your IP is being traced right now so you better prepare for the storm, maggot. The storm that wipes out the pathetic little thing you call your life. You're fucking dead, kid. I can be anywhere, anytime, and I can kill you in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable ass off the face of the continent, you little shit. If only you could have known what unholy retribution your little \"clever\" comment was about to bring down upon you, maybe you would have held your fucking tongue. But you couldn't, you didn't, and now you're paying the price, you goddamn idiot. I will shit fury all over you and you will drown in it. You're fucking dead, kiddo. "
str3 = "This is for Rachel you big fat white nasty smelling fat bitch why you took me off the motherfuckin schedule with your trifflin dirty white racist ass you big fat bitch oompa loompa body ass bitch I'm coming up there and I'm gonna beat the fuck out of you bitch and don't even call the police today cause I'm gonna come up there unexpected and wait on your motherfuckin ass bitch im coming to beat the fuck out of you bitch cause you did that on purpose with your aundry racist white ass thin haired bitch watch I'm coming up there to fuck you up bitch I'm telling you watch I know what kind of car you drive I'm gonna wait on you and I'm gonna beat your ass bitch cause Imma show you not to play with Jasmine Collin's money bitch thats the first thing you did and you got me fucked up cause bitch I told you what the fuck was going on you white mother fuckers hate to see black people doing good or doing good or doing anything for them motherfuckin selves ugly fat white bitch watch I'm telling you I'm coming up there to beat your mother fucking ass thin haired smelling white dog smelling ass bitch watch I'm coming to fuck you up cause you got me fucked up gonna sit up there and try to do that little aundry was shit bitch you aundry since the first day I came up there talking about a bitch that had on pajamas but you walking around here in some ten dollar ass jeans on dirty dusty white bitch sit up there behind that counter smelling like cheese bitch stinky fat white ass bitch and you gonna try to not answer this phone I'm coming to fuck you up I'm telling you you better remember who I am cause bitch you gonna run when you see me cause I'm coming to fuck you up bitch wanna sit up and play me about my motherfuckin money wanna play about my motherfuckin money bitch you gonna sit up there and try to do that bitch little do you know little do you know I know enough people watch I'm coming to fuck you up I'm promise you that i promise you I'm coming to fuck you up you fat stinky white bitch thin haired yellow yuck mouth nasty mouth ass bitch you stink you smell like fucking cheese and you got that trifflin ass attitude Imma beat that attitude up out you bitch watch you treat everybody like that all these old black people that you do like that you in the wrong position you trifflin ass racist ass white bitch thats why don't nobody fuck with you cause you trifflin and you racist bitch sit up there and did all this shit and I told you what the fuck was going on gonna tell me that I worked at that motherfuckin job when I'm telling you the fuck I didn't bitch why the fuck would I lie about some shit like that watch I finna come there and beat your motherfuckin ass you better not get out that car bitch I'm telling you fucking- "
str4 = "Not funny I didn't laugh. Your joke is so bad I would have preferred the joke went over my head and you gave up re-telling me the joke. To be honest this is a horrid attempt at trying to get a laugh out of me. Not a chuckle, not a hehe, not even a subtle burst of air out of my esophagus. Science says before you laugh your brain preps your face muscles but I didn't even feel the slightest twitch. 0/10 this joke is so bad I cannot believe anyone legally allowed you to be creative at all. The amount of brain power you must have put into that joke has the potential to power every house on Earth. Get a personality and learn how to make jokes, read a book. I'm not saying this to be funny I genuinely mean it on how this is just bottom barrel embarrassment at comedy. You've single handedly killed humor and every comedic act on the planet. I'm so disappointed that society has failed as a whole in being able to teach you how to be funny. Honestly if I put in all my power and time to try and make your joke funny it would require Einstein himself to build a device to strap me into so I can be connected to the energy of a billion stars to do it, and even then all that joke would get from people is a subtle scuff. You're lucky I still have the slightest of empathy for you after telling that joke otherwise I would have committed every war crime in the book just to prevent you from attempting any humor ever again. We should put that joke in text books so future generations can be wary of becoming such an absolute comedic failure. Im disappointed, hurt, and outright offended that my precious time has been wasted in my brain understanding that joke. In the time that took I was planning on helping kids who have been orphaned, but because of that you've waisted my time explaining the obscene integrity of your terrible attempt at comedy. Now those kids are suffering without meals and there's nobody to blame but you. I hope you're happy with what you have done and I truly hope you can move on and learn from this piss poor attempt "
for char in str4:
    if (char == " "):
        keyboard.press(Key.enter)
        keyboard.release(Key.enter)
    else:
        keyboard.press(char)
        keyboard.release(char)